package ca.etsmtl.applets.etsmobile.model;

//----------------------------------------------------
//
//Generated by www.easywsdl.com
//Version: 4.0.1.0
//
//Created by Quasar Development at 03-09-2014
//
//---------------------------------------------------



import java.util.Hashtable;
import java.util.Vector;

import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import ca.etsmtl.applets.etsmobile.http.soap.ExtendedSoapSerializationEnvelope;


public class ArrayOfSeances extends Vector<Seances> implements KvmSerializable
{
  
  public ArrayOfSeances(){}
  
  public ArrayOfSeances(AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
  {
      if (inObj == null)
          return;
      SoapObject soapObject=(SoapObject)inObj;
      int size = soapObject.getPropertyCount();
      for (int i0=0;i0< size;i0++)
      {
          Object obj = soapObject.getProperty(i0);
          if (obj!=null && obj instanceof AttributeContainer)
          {
              AttributeContainer j = (AttributeContainer) soapObject.getProperty(i0);
              Seances j1= (Seances)envelope.get(j,Seances.class);
              add(j1);
          }
      }
}
  
  @Override
  public java.lang.Object getProperty(int arg0) {
      return this.get(arg0);
  }
  
  @Override
  public int getPropertyCount() {
      return this.size();
  }
  
  @Override
  public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
      info.name = "Seances";
      info.type = Seances.class;
  	info.namespace= "http://etsmtl.ca/";
  }
  
  @Override
  public void setProperty(int arg0, java.lang.Object arg1) {
  }

}