package ca.etsmtl.applets.etsmobile.model;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 15-01-2014
//
//---------------------------------------------------

import java.util.Hashtable;

import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import ca.etsmtl.applets.etsmobile.http.soap.ExtendedSoapSerializationEnvelope;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "horaire_activite")
public class HoraireActivite extends AttributeContainer implements KvmSerializable {

	@DatabaseField
	public String sigle;

	@DatabaseField
	public String groupe;

	@DatabaseField
	public String jour;
	
	@DatabaseField
	public String journee;
	
	
	@DatabaseField
	public String codeActivite;
	@DatabaseField
	public String nomActivite;
	@DatabaseField
	public String activitePrincipale;
	
	@DatabaseField
	public String heureDebut;
	
	@DatabaseField
	public String heureFin;
	@DatabaseField
	public String local;
	@DatabaseField
	public String titreCours;

	@DatabaseField(id = true)
	public String id;

	public HoraireActivite() {
	}



	
	public HoraireActivite(AttributeContainer inObj, ExtendedSoapSerializationEnvelope envelope) {

		if (inObj == null)
			return;

		SoapObject soapObject = (SoapObject) inObj;

		if (soapObject.hasProperty("sigle")) {
			Object obj = soapObject.getProperty("sigle");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					sigle = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				sigle = (String) obj;
			}
		}
		if (soapObject.hasProperty("groupe")) {
			Object obj = soapObject.getProperty("groupe");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					groupe = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				groupe = (String) obj;
			}
		}
		if (soapObject.hasProperty("jour")) {
			Object obj = soapObject.getProperty("jour");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					jour = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				jour = (String) obj;
			}
		}
		if (soapObject.hasProperty("journee")) {
			Object obj = soapObject.getProperty("journee");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					journee = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				journee = (String) obj;
			}
		}
		if (soapObject.hasProperty("codeActivite")) {
			Object obj = soapObject.getProperty("codeActivite");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					codeActivite = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				codeActivite = (String) obj;
			}
		}
		if (soapObject.hasProperty("nomActivite")) {
			Object obj = soapObject.getProperty("nomActivite");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					nomActivite = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				nomActivite = (String) obj;
			}
		}
		if (soapObject.hasProperty("activitePrincipale")) {
			Object obj = soapObject.getProperty("activitePrincipale");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					activitePrincipale = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				activitePrincipale = (String) obj;
			}
		}
		if (soapObject.hasProperty("heureDebut")) {
			Object obj = soapObject.getProperty("heureDebut");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					heureDebut = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				heureDebut = (String) obj;
			}
		}
		if (soapObject.hasProperty("heureFin")) {
			Object obj = soapObject.getProperty("heureFin");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					heureFin = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				heureFin = (String) obj;
			}
		}
		if (soapObject.hasProperty("local")) {
			Object obj = soapObject.getProperty("local");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					local = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				local = (String) obj;
			}
		}
		if (soapObject.hasProperty("titreCours")) {
			Object obj = soapObject.getProperty("titreCours");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					titreCours = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				titreCours = (String) obj;
			}
		}

	}
	

	@Override
	public Object getProperty(int propertyIndex) {
		if (propertyIndex == 0) {
			return sigle;
		}
		if (propertyIndex == 1) {
			return groupe;
		}
		if (propertyIndex == 2) {
			return jour;
		}
		if (propertyIndex == 3) {
			return journee;
		}
		if (propertyIndex == 4) {
			return codeActivite;
		}
		if (propertyIndex == 5) {
			return nomActivite;
		}
		if (propertyIndex == 6) {
			return activitePrincipale;
		}
		if (propertyIndex == 7) {
			return heureDebut;
		}
		if (propertyIndex == 8) {
			return heureFin;
		}
		if (propertyIndex == 9) {
			return local;
		}
		if (propertyIndex == 10) {
			return titreCours;
		}
		return null;
	}

	@Override
	public int getPropertyCount() {
		return 11;
	}

	@Override
	public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		if (propertyIndex == +0) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "sigle";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +1) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "groupe";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +2) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "jour";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +3) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "journee";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +4) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "codeActivite";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +5) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "nomActivite";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +6) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "activitePrincipale";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +7) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "heureDebut";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +8) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "heureFin";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +9) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "local";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +10) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "titreCours";
			info.namespace = "http://etsmtl.ca/";
		}
	}

	@Override
	public void setProperty(int arg0, Object arg1) {
	}
	
	

}
