package ca.etsmtl.applets.etsmobile.model;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 15-01-2014
//
//---------------------------------------------------

public class OperationResult<T> {
	public java.lang.Exception Exception;
	public T Result;
	public Object Tag;
}
