package ca.etsmtl.applets.etsmobile.model;

//----------------------------------------------------
//
//Generated by www.easywsdl.com
//Version: 4.0.1.0
//
//Created by Quasar Development at 03-09-2014
//
//---------------------------------------------------


import com.google.android.gms.wearable.DataMap;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

import ca.etsmtl.applets.etsmobile.http.soap.ExtendedSoapSerializationEnvelope;

@DatabaseTable(tableName = "seances")
public class Seances extends AttributeContainer implements KvmSerializable, IHoraireRows
{
  
  @DatabaseField
  public String dateDebut;
  
  @DatabaseField
  public String dateFin;
  
  @DatabaseField
  public String coursGroupe;
  
  @DatabaseField
  public String nomActivite;
  
  @DatabaseField
  public String local;
  
  @DatabaseField
  public String descriptionActivite;
  
  @DatabaseField
  public String libelleCours;
  
  @DatabaseField(id = true)
  public String id;

  public Seances ()
  {
  }

    public void getData(DataMap map){
        dateDebut = map.getString("dateDebut");
        dateFin = map.getString("dateFin");
        coursGroupe = map.getString("coursGroupe");
        nomActivite = map.getString("nomActivite");
        local = map.getString("local");
        descriptionActivite = map.getString("descriptionActivite");
        libelleCours = map.getString("libelleCours");
    }

    public DataMap putData(){
        DataMap map = new DataMap();
        map.putString("dateDebut", dateDebut);
        map.putString("dateFin", dateFin);
        map.putString("coursGroupe", coursGroupe);
        map.putString("nomActivite", nomActivite);
        map.putString("local", local);
        map.putString("descriptionActivite", descriptionActivite);
        map.putString("libelleCours", libelleCours);
        return map;
    }

  public Seances (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
  {
	    
	  if (inObj == null)
          return;

      SoapObject soapObject=(SoapObject)inObj; 
      
      if (soapObject.hasProperty("dateDebut"))
      {	
	      Object obj = soapObject.getProperty("dateDebut");
          if (obj != null && obj.getClass().equals(SoapPrimitive.class))
          {
              SoapPrimitive j =(SoapPrimitive) obj;
              if(j.toString()!=null)
              {
                  this.dateDebut =j.toString();
              }
	        }
	        else if (obj!= null && obj instanceof String){
              this.dateDebut = (String)obj;
          }    
      }
      if (soapObject.hasProperty("dateFin"))
      {	
	        java.lang.Object obj = soapObject.getProperty("dateFin");
          if (obj != null && obj.getClass().equals(SoapPrimitive.class))
          {
              SoapPrimitive j =(SoapPrimitive) obj;
              if(j.toString()!=null)
              {
                  this.dateFin = j.toString();
              }
	        }
	        else if (obj!= null && obj instanceof String){
              this.dateFin = (String)obj;
          }    
      }
      if (soapObject.hasProperty("coursGroupe"))
      {	
	        java.lang.Object obj = soapObject.getProperty("coursGroupe");
          if (obj != null && obj.getClass().equals(SoapPrimitive.class))
          {
              SoapPrimitive j =(SoapPrimitive) obj;
              if(j.toString()!=null)
              {
                  this.coursGroupe = j.toString();
              }
	        }
	        else if (obj!= null && obj instanceof String){
              this.coursGroupe = (String)obj;
          }    
      }
      if (soapObject.hasProperty("nomActivite"))
      {	
	        java.lang.Object obj = soapObject.getProperty("nomActivite");
          if (obj != null && obj.getClass().equals(SoapPrimitive.class))
          {
              SoapPrimitive j =(SoapPrimitive) obj;
              if(j.toString()!=null)
              {
                  this.nomActivite = j.toString();
              }
	        }
	        else if (obj!= null && obj instanceof String){
              this.nomActivite = (String)obj;
          }    
      }
      if (soapObject.hasProperty("local"))
      {	
	        java.lang.Object obj = soapObject.getProperty("local");
          if (obj != null && obj.getClass().equals(SoapPrimitive.class))
          {
              SoapPrimitive j =(SoapPrimitive) obj;
              if(j.toString()!=null)
              {
                  this.local = j.toString();
              }
	        }
	        else if (obj!= null && obj instanceof String){
              this.local = (String)obj;
          }    
      }
      if (soapObject.hasProperty("descriptionActivite"))
      {	
	        java.lang.Object obj = soapObject.getProperty("descriptionActivite");
          if (obj != null && obj.getClass().equals(SoapPrimitive.class))
          {
              SoapPrimitive j =(SoapPrimitive) obj;
              if(j.toString()!=null)
              {
                  this.descriptionActivite = j.toString();
              }
	        }
	        else if (obj!= null && obj instanceof String){
              this.descriptionActivite = (String)obj;
          }    
      }
      if (soapObject.hasProperty("libelleCours"))
      {	
	        java.lang.Object obj = soapObject.getProperty("libelleCours");
          if (obj != null && obj.getClass().equals(SoapPrimitive.class))
          {
              SoapPrimitive j =(SoapPrimitive) obj;
              if(j.toString()!=null)
              {
                  this.libelleCours = j.toString();
              }
	        }
	        else if (obj!= null && obj instanceof String){
              this.libelleCours = (String)obj;
          }    
      }


  }

  @Override
  public java.lang.Object getProperty(int propertyIndex) {
      //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
      //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
      if(propertyIndex==0)
      {
          return dateDebut;
      }
      if(propertyIndex==1)
      {
          return dateFin;
      }
      if(propertyIndex==2)
      {
          return coursGroupe;
      }
      if(propertyIndex==3)
      {
          return nomActivite;
      }
      if(propertyIndex==4)
      {
          return local;
      }
      if(propertyIndex==5)
      {
          return descriptionActivite;
      }
      if(propertyIndex==6)
      {
          return libelleCours;
      }
      return null;
  }


  @Override
  public int getPropertyCount() {
      return 7;
  }

  @Override
  public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
  {
      if(propertyIndex==0)
      {
          info.type = PropertyInfo.STRING_CLASS;
          info.name = "dateDebut";
          info.namespace= "http://etsmtl.ca/";
      }
      if(propertyIndex==1)
      {
          info.type = PropertyInfo.STRING_CLASS;
          info.name = "dateFin";
          info.namespace= "http://etsmtl.ca/";
      }
      if(propertyIndex==2)
      {
          info.type = PropertyInfo.STRING_CLASS;
          info.name = "coursGroupe";
          info.namespace= "http://etsmtl.ca/";
      }
      if(propertyIndex==3)
      {
          info.type = PropertyInfo.STRING_CLASS;
          info.name = "nomActivite";
          info.namespace= "http://etsmtl.ca/";
      }
      if(propertyIndex==4)
      {
          info.type = PropertyInfo.STRING_CLASS;
          info.name = "local";
          info.namespace= "http://etsmtl.ca/";
      }
      if(propertyIndex==5)
      {
          info.type = PropertyInfo.STRING_CLASS;
          info.name = "descriptionActivite";
          info.namespace= "http://etsmtl.ca/";
      }
      if(propertyIndex==6)
      {
          info.type = PropertyInfo.STRING_CLASS;
          info.name = "libelleCours";
          info.namespace= "http://etsmtl.ca/";
      }
  }

    @Override
    public String getDateDebut() {
        return dateDebut;
    }

    @Override
    public String getDateFin() {
        return dateFin;
    }

    @Override
  public void setProperty(int arg0, java.lang.Object arg1)
  {
  }

}