language: android
cache:
  directories:
    - $HOME/.gradle/caches/2.13
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
android:
  components:
    - tools
    - build-tools-23.0.3
    - platform-tools
    - android-23
    
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
    


script:
   - ./gradlew assembleDebug -PdisablePreDex
