package ca.etsmtl.applets.etsmobile.http.soap;

import ca.etsmtl.applets.etsmobile.model.OperationResult;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 15-01-2014
//
//---------------------------------------------------

public interface IServiceEvents {
	public void Starting();

	public void Completed(OperationResult result);
}
