package ca.etsmtl.applets.etsmobile.model;

//----------------------------------------------------
//
//Generated by www.easywsdl.com
//Version: 4.0.1.0
//
//Created by Quasar Development at 03-09-2014
//
//---------------------------------------------------



import org.ksoap2.serialization.*;

import ca.etsmtl.applets.etsmobile.http.soap.ExtendedSoapSerializationEnvelope;

import java.util.Vector;
import java.util.Hashtable;


public class ArrayOfHoraireExamenFinal extends Vector< HoraireExamenFinal> implements KvmSerializable
{
  
  public ArrayOfHoraireExamenFinal(){}
  
  public ArrayOfHoraireExamenFinal(AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
  {
      if (inObj == null)
          return;
      SoapObject soapObject=(SoapObject)inObj;
      int size = soapObject.getPropertyCount();
      for (int i0=0;i0< size;i0++)
      {
          Object obj = soapObject.getProperty(i0);
          if (obj!=null && obj instanceof AttributeContainer)
          {
              AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
              HoraireExamenFinal j1= (HoraireExamenFinal)envelope.get(j,HoraireExamenFinal.class);
              add(j1);
          }
      }
}
  
  @Override
  public Object getProperty(int arg0) {
      return this.get(arg0);
  }
  
  @Override
  public int getPropertyCount() {
      return this.size();
  }
  
  @Override
  public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
      info.name = "HoraireExamenFinal";
      info.type = HoraireExamenFinal.class;
  	info.namespace= "http://etsmtl.ca/";
  }
  
  @Override
  public void setProperty(int arg0, java.lang.Object arg1) {
  }

}