package ca.etsmtl.applets.etsmobile.model;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.3.1
//
// Created by Quasar Development at 03-03-2014
//
//---------------------------------------------------

import java.util.Hashtable;

import org.joda.time.DateTime;
import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import ca.etsmtl.applets.etsmobile.http.soap.ExtendedSoapSerializationEnvelope;
import ca.etsmtl.applets.etsmobile.http.soap.Helper;

public class FicheEmployeDate extends AttributeContainer implements
		KvmSerializable {

	public Integer Id = 0;

	public DateTime DateModif;

	public FicheEmployeDate() {
	}

	public FicheEmployeDate(AttributeContainer inObj,
			ExtendedSoapSerializationEnvelope envelope) {

		if (inObj == null)
			return;

		SoapObject soapObject = (SoapObject) inObj;

		if (soapObject.hasProperty("Id")) {
			Object obj = soapObject.getProperty("Id");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					this.Id = Integer.parseInt(j.toString());
				}
			} else if (obj != null && obj instanceof Integer) {
				this.Id = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("DateModif")) {
			Object obj = soapObject.getProperty("DateModif");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					this.DateModif = Helper.ConvertFromWebService(j.toString());
				}
			} else if (obj != null && obj instanceof DateTime) {
				this.DateModif = (DateTime) obj;
			}
		}

	}

	@Override
	public Object getProperty(int propertyIndex) {
		if (propertyIndex == 0) {
			return Id;
		}
		if (propertyIndex == 1) {
			return DateModif;
		}
		return null;
	}

	@Override
	public int getPropertyCount() {
		return 2;
	}

	@Override
	public void getPropertyInfo(int propertyIndex,
			@SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		if (propertyIndex == +0) {
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "Id";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == +1) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "DateModif";
			info.namespace = "http://etsmtl.ca/";
		}
	}

	@Override
	public void setProperty(int arg0, Object arg1) {
	}

}
