package ca.etsmtl.applets.etsmobile.model;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 15-01-2014
//
//---------------------------------------------------

import java.util.Hashtable;

import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import ca.etsmtl.applets.etsmobile.http.soap.ExtendedSoapSerializationEnvelope;

public class ListeDesElementsEvaluation extends DonneesRetournees implements
		KvmSerializable {

	public String noteACeJour;

	public String scoreFinalSur100;

	public String moyenneClasse;

	public String ecartTypeClasse;

	public String medianeClasse;

	public String rangCentileClasse;

	public String noteACeJourElementsIndividuels;

	public String noteSur100PourElementsIndividuels;

	public ArrayOfElementEvaluation liste = new ArrayOfElementEvaluation();

	public ListeDesElementsEvaluation() {
	}

	public ListeDesElementsEvaluation(AttributeContainer inObj,
			ExtendedSoapSerializationEnvelope envelope) {
		super(inObj, envelope);
		if (inObj == null)
			return;

		SoapObject soapObject = (SoapObject) inObj;

		if (soapObject.hasProperty("noteACeJour")) {
			Object obj = soapObject.getProperty("noteACeJour");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					noteACeJour = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				noteACeJour = (String) obj;
			}
		}
		if (soapObject.hasProperty("scoreFinalSur100")) {
			Object obj = soapObject.getProperty("scoreFinalSur100");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					scoreFinalSur100 = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				scoreFinalSur100 = (String) obj;
			}
		}
		if (soapObject.hasProperty("moyenneClasse")) {
			Object obj = soapObject.getProperty("moyenneClasse");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					moyenneClasse = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				moyenneClasse = (String) obj;
			}
		}
		if (soapObject.hasProperty("ecartTypeClasse")) {
			Object obj = soapObject.getProperty("ecartTypeClasse");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					ecartTypeClasse = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				ecartTypeClasse = (String) obj;
			}
		}
		if (soapObject.hasProperty("medianeClasse")) {
			Object obj = soapObject.getProperty("medianeClasse");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					medianeClasse = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				medianeClasse = (String) obj;
			}
		}
		if (soapObject.hasProperty("rangCentileClasse")) {
			Object obj = soapObject.getProperty("rangCentileClasse");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					rangCentileClasse = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				rangCentileClasse = (String) obj;
			}
		}
		if (soapObject.hasProperty("noteACeJourElementsIndividuels")) {
			Object obj = soapObject
					.getProperty("noteACeJourElementsIndividuels");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					noteACeJourElementsIndividuels = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				noteACeJourElementsIndividuels = (String) obj;
			}
		}
		if (soapObject.hasProperty("noteSur100PourElementsIndividuels")) {
			Object obj = soapObject
					.getProperty("noteSur100PourElementsIndividuels");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				if (j.toString() != null) {
					noteSur100PourElementsIndividuels = j.toString();
				}
			} else if (obj != null && obj instanceof String) {
				noteSur100PourElementsIndividuels = (String) obj;
			}
		}
		if (soapObject.hasProperty("liste")) {
			SoapObject j = (SoapObject) soapObject.getProperty("liste");
			liste = new ArrayOfElementEvaluation(j, envelope);
		}

	}

	@Override
	public Object getProperty(int propertyIndex) {
		int count = super.getPropertyCount();
		if (propertyIndex == count + 0) {
			return noteACeJour;
		}
		if (propertyIndex == count + 1) {
			return scoreFinalSur100;
		}
		if (propertyIndex == count + 2) {
			return moyenneClasse;
		}
		if (propertyIndex == count + 3) {
			return ecartTypeClasse;
		}
		if (propertyIndex == count + 4) {
			return medianeClasse;
		}
		if (propertyIndex == count + 5) {
			return rangCentileClasse;
		}
		if (propertyIndex == count + 6) {
			return noteACeJourElementsIndividuels;
		}
		if (propertyIndex == count + 7) {
			return noteSur100PourElementsIndividuels;
		}
		if (propertyIndex == count + 8) {
			return liste;
		}
		return super.getProperty(propertyIndex);
	}

	@Override
	public int getPropertyCount() {
		return super.getPropertyCount() + 9;
	}

	@Override
	public void getPropertyInfo(int propertyIndex,
			@SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		int count = super.getPropertyCount();
		if (propertyIndex == count + 0) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "noteACeJour";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 1) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "scoreFinalSur100";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 2) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "moyenneClasse";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 3) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "ecartTypeClasse";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 4) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "medianeClasse";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 5) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "rangCentileClasse";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 6) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "noteACeJourElementsIndividuels";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 7) {
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "noteSur100PourElementsIndividuels";
			info.namespace = "http://etsmtl.ca/";
		}
		if (propertyIndex == count + 8) {
			info.type = PropertyInfo.VECTOR_CLASS;
			info.name = "liste";
			info.namespace = "http://etsmtl.ca/";
		}
		super.getPropertyInfo(propertyIndex, arg1, info);
	}

	@Override
	public void setProperty(int arg0, Object arg1) {
	}

}
